# Generated by Django 2.1.3 on 2018-11-04 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superprice_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruits',
            old_name='left',
            new_name='sold',
        ),
    ]
