# Generated by Django 2.1.3 on 2018-11-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superprice_api', '0004_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruits',
            name='critical_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fruits',
            name='demand',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fruits',
            name='desired_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fruits',
            name='remaining_days',
            field=models.IntegerField(default=0),
        ),
    ]
