# Generated by Django 2.1.3 on 2018-11-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superprice_api', '0005_auto_20181104_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruits',
            name='demand',
            field=models.FloatField(default=0),
        ),
    ]
